- name: stop old services
  systemd:
    name: "{{ item }}"
    daemon_reload: no
    enabled: no
    state: stopped
  with_items:
    - grafana
    - suid
    - prometheus
    - node_exporter
    - nginx
  failed_when: false

- name: delete old directories
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /var/lib/grafana
    - /var/lib/prometheus
  failed_when: false

- name: Gather facts on listening ports
  community.general.listen_ports_facts:
  register: result

- set_fact:
    tcp_whitelist:
      - 9100
      - 9090
      - 3000
      - 80
      - 9000
      - 9184
      - 9001

- set_fact:
    tcp_listen_violations: "{{ ansible_facts.tcp_listen | selectattr('port', 'in', tcp_whitelist) | list }}"

- debug: var=tcp_listen_violations

- debug:
    msg: "Needed port(s) in use"
  failed_when:  tcp_listen_violations | length > 0

