- hosts: sui
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - { role: sui_node, tags: [sui_node] }
    - { role: docker, tags: [docker] }
    - { role: node_exporter, tags: [node_exporter] }
    - { role: prometheus, tags: [prometheus] }
    - { role: grafana, tags: [grafana] }
    - { role: nginx, tags: [nginx] }



