- hosts: localhost
  roles:
    - { role: check_install, tags: [ check_install, reinstall] }
    - { role: sui_node, tags: [sui_node, install, reinstall] }
    - { role: docker, tags: [docker, install, reinstall] }
    - { role: node_exporter, tags: [node_exporter, install, reinstall] }
    - { role: prometheus, tags: [prometheus, install, reinstall] }
    - { role: grafana, tags: [grafana, install, reinstall] }
    - { role: nginx, tags: [ nginx, install, reinstall] }



